"""empty message

Revision ID: 181d30bc2118
Revises: 3dd1d04a6e2b
Create Date: 2018-03-02 22:12:43.310495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181d30bc2118'
down_revision = '3dd1d04a6e2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile', 'password')
    # ### end Alembic commands ###
